module.exports = Object.freeze({
    QUALITY: {
        1: "Genuine",
        3: "Vintage",
        5: "Unusual",
        6: "Unique",
        7: "Community",
        8: "Valve",
        9: "Self-Made",
        11: "Strange",
        13: "Haunted",
        14: "Collector's",
        15: "Decorated Weapon",

        "Genuine": 1,
        "Vintage": 3,
        "Unusual": 5,
        "Unique": 6,
        "Commmunity": 7,
        "Valve": 8,
        "Self-Made": 9,
        "Strange": 11,
        "Haunted": 13,
        "Collector's": 14,
        "Decorated Weapon": 15,
    },
    KILLSTREAK: {
        0: "",
        1: "Killstreak ",
        2: "Specialized Killstreak ",
        3: "Professional Killstreak ",

        "Killstreak": 1,
        "Specialized Killstreak": 2,
        "Professional Killstreak": 3,
    },
    UNUSUAL_EFFECT: {
        "1": "Particle 1",
        "2": "Flying Bits",
        "3": "Nemesis Burst",
        "4": "Community Sparkle",
        "5": "Holy Glow",
        "6": "Green Confetti",
        "7": "Purple Confetti",
        "8": "Haunted Ghosts",
        "9": "Green Energy",
        "10": "Purple Energy",
        "11": "Circling TF Logo",
        "12": "Massed Flies",
        "13": "Burning Flames",
        "14": "Scorching Flames",
        "15": "Searing Plasma",
        "16": "Vivid Plasma",
        "17": "Sunbeams",
        "18": "Circling Peace Sign",
        "19": "Circling Heart",
        "20": "Map Stamps",
        "28": "Genteel Smoke",
        "29": "Stormy Storm",
        "30": "Blizzardy Storm",
        "31": "Nuts n' Bolts",
        "32": "Orbiting Planets",
        "33": "Orbiting Fire",
        "34": "Bubbling",
        "35": "Smoking",
        "36": "Steaming",
        "37": "Flaming Lantern",
        "38": "Cloudy Moon",
        "39": "Cauldron Bubbles",
        "40": "Eerie Orbiting Fire",
        "43": "Knifestorm",
        "44": "Misty Skull",
        "45": "Harvest Moon",
        "46": "It's A Secret To Everybody",
        "47": "Stormy 13th Hour",
        "55": "Attrib_Particle55",
        "56": "Kill-a-Watt",
        "57": "Terror-Watt",
        "58": "Cloud 9",
        "59": "Aces High",
        "60": "Dead Presidents",
        "61": "Miami Nights",
        "62": "Disco Beat Down",
        "63": "Phosphorous",
        "64": "Sulphurous",
        "65": "Memory Leak",
        "66": "Overclocked",
        "67": "Electrostatic",
        "68": "Power Surge",
        "69": "Anti-Freeze",
        "70": "Time Warp",
        "71": "Green Black Hole",
        "72": "Roboactive",
        "73": "Arcana",
        "74": "Spellbound",
        "75": "Chiroptera Venenata",
        "76": "Poisoned Shadows",
        "77": "Something Burning This Way Comes",
        "78": "Hellfire",
        "79": "Darkblaze",
        "80": "Demonflame",
        "81": "Bonzo The All-Gnawing",
        "82": "Amaranthine",
        "83": "Stare From Beyond",
        "84": "The Ooze",
        "85": "Ghastly Ghosts Jr",
        "86": "Haunted Phantasm Jr",
        "87": "Frostbite",
        "88": "Molten Mallard",
        "89": "Morning Glory",
        "90": "Death at Dusk",
        "91": "Abduction",
        "92": "Atomic",
        "93": "Subatomic",
        "94": "Electric Hat Protector",
        "95": "Magnetic Hat Protector",
        "96": "Voltaic Hat Protector",
        "97": "Galactic Codex",
        "98": "Ancient Codex",
        "99": "Nebula",
        "100": "Death by Disco",
        "101": "It's a mystery to everyone",
        "102": "It's a puzzle to me",
        "103": "Ether Trail",
        "104": "Nether Trail",
        "105": "Ancient Eldritch",
        "106": "Eldritch Flame",
        "107": "Neutron Star",
        "108": "Tesla Coil",
        "109": "Starstorm Insomnia",
        "110": "Starstorm Slumber",
        "701": "Hot",
        "702": "Isotope",
        "703": "Cool",
        "704": "Energy Orb",
        "2001": "Attrib_Particle2001",
        "2002": "Attrib_Particle2002",
        "2003": "Attrib_Particle2003",
        "2004": "Attrib_Particle2004",
        "2005": "Attrib_Particle2005",
        "2006": "Attrib_Particle2006",
        "2007": "Attrib_Particle2007",
        "2008": "Attrib_Particle2008",
        "3001": "Showstopper",
        "3002": "Showstopper",
        "3003": "Holy Grail",
        "3004": "'72",
        "3005": "Fountain of Delight",
        "3006": "Screaming Tiger",
        "3007": "Skill Gotten Gains",
        "3008": "Midnight Whirlwind",
        "3009": "Silver Cyclone",
        "3010": "Mega Strike",
        "3011": "Haunted Phantasm",
        "3012": "Ghastly Ghosts",
        "3013": "Hellish Inferno",
        "3014": "Spectral Swirl",
        "3015": "Infernal Flames",
        "3016": "Infernal Smoke",
        "22001": "Attrib_Particle22001",
        "22002": "Attrib_Particle22002",
        "22003": "Attrib_Particle22003",
        "22004": "Attrib_Particle22004",
        "22005": "Attrib_Particle22005",
        "22006": "Attrib_Particle22006",
        "22007": "Attrib_Particle22007",
        "22008": "Attrib_Particle22008"
    },
});
